// <auto-generated />
namespace Test_app_BrightEye.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SortNumbers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SortNumbers));
        
        string IMigrationMetadata.Id
        {
            get { return "202105151433249_SortNumbers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
